export const MATCH_CONFIG = {
  STOCKS: 3,
  RESPAWN_INVINCIBILITY_FRAMES: 180,
  RESPAWN_PLATFORM_Y: 200,
  RESPAWN_DELAY_FRAMES: 120,
  MAX_PLAYERS: 4,
  MIN_PLAYERS: 2,
  COUNTDOWN_SECONDS: 3,
  RESULT_DISPLAY_SECONDS: 5,
} as const;
