export const PHYSICS = {
  GRAVITY: 0.65,
  TERMINAL_VELOCITY: 18,
  JUMP_VELOCITY: -16,
  SHORT_HOP_VELOCITY: -10,
  SHORT_HOP_THRESHOLD_FRAMES: 3,
  AIR_SPEED: 0.9,
  AIR_FRICTION: 0.85,
  GROUND_FRICTION: 0.7,
  FAST_FALL_MULTIPLIER: 1.8,
  RUN_SPEED: 6.5,
  WALK_SPEED: 3.5,
  DOUBLE_JUMP_VELOCITY: -14,
  JUMPSQUAT_FRAMES: 3,
  HURTBOX_RADIUS: 28,
  FIGHTER_WEIGHT: 100,
  SHIELD_MAX_HEALTH: 100,
  SHIELD_DRAIN_PER_FRAME: 0.4,
  SHIELD_REGEN_PER_FRAME: 0.2,
  SHIELD_BREAK_STUN_FRAMES: 150,
} as const;

export type Physics = typeof PHYSICS;
